---
title: "WarmUp1"
output: github_document
---

# Ingredients
* 1/4 cup white vine vinegar
* 8 eggs
* extra-virgin oil
* 8 thick slices Canadian bacon
* 4 English muffins, fork split
* Hollandaise Sauce, recipe follows
* 4 cups mesclun mix
* Juice of 1/2 to 1 lemon
* Kosher salt

## Special kitchen tools
* Large, wide pot
* Slotted spoon
* Saute Pan

#### Instructions
1. Fill pot with water
    1. Bring to *boil*
1. **Crack eggs and gently drop each egg in the water**
1. Use spoon to remove eggs and put them into a bowl of cold water
1. Coat saute pan with olive oil and bring to medium heat
1. Add slices of Canadian bacon and cook them on both sides until they are hot but not brown
1. Toast English Muffins
1. Place 1 slice Canadian bacon on each English muffin
1. Warm up egg poaching liquid and place eggs in the water for 1 minute 
1. Remove eggs from warm water
  1. Place 1 egg on each English muffin

![Eggs Benedict]
(http://www.simplyrecipes.com/wp-content/uploads/2010/04/eggs-benedict-horiz-a-1600.jpg)

[Eggs Benedict](http://www.simplyrecipes.com/wp-content/uploads/2010/04/eggs-benedict-horiz-a-1600.jpg)

As Anne Burrell said:

> This dish only takes one hour to complete.

Prep | Cook
-----| -----
30 min | 30 min

***

# Quadratic Formula

Quadratic Equation: $x=-b \pm \sqrt{b^2 - 4ac} \over 2a$
